apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: springskaffold
build:
  artifacts:
  - image: springboot-k8s-example
    jib: {}

deploy:
  helm:
    releases:
    - name: rest-service
      chartPath: rest-service
      valuesFiles:
      - rest-service/values.yaml
      version: 0.1.0
