apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: springskaffold

build:
  artifacts:
  - image: springboot-k8s-example
    docker:
      dockerfile: Dockerfile

manifests:
  rawYaml:
  - k8s/deployment.yaml
  - k8s/service.yaml
